version: "3"

networks:
  laravel:

services:
  nginx:
    container_name: todoer-nginx
    image: nginx:stable-alpine
    ports:
      - "5055:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: todoer-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "6306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: todoer
      MYSQL_USER: root_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build: ./
    container_name: todoer-php
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  mailhog:
    image: "mailhog/mailhog:latest"
    container_name: todoer-mailhog
    ports:
      - "${FORWARD_MAILHOG_PORT:-2025}:1025"
      - "${FORWARD_MAILHOG_DASHBOARD_PORT:-9025}:8025"
    networks:
      - laravel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: todoer-pma
    links:
      - mysql
    environment:
      PMA_HOST: todoer-mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8082:80
    networks:
      - laravel
    depends_on:
      - php
      - mysql
